In [9]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output


values = np.random.randint(1, 10 ,  size = 5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [10]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)


4.84 s ± 382 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [12]:
%timeit (1.0 / big_array)

7.41 ms ± 683 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [16]:
x = np.arange(9).reshape((3 , 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [17]:
x = np.arange(4)
print("x  =", x)
print("x + 5=", x+ 5)

x  = [0 1 2 3]
x + 5= [5 6 7 8]


In [ ]:
np.add(x,2)

In [ ]:
theta = np.linspace(0, np.pi, 3)

In [ ]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

In [1]:
from scipy import special

In [2]:
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [18]:
x = np.arange(1, 6)
np.add.reduce(x)

15